### ISSUE TITLE
Compiler appears to infinite loop on windows

### ISSUE THREAD

**Issue by AnthonySuper** [jonascarpay/apecs#23]
I'm trying to compile `apecs` as a dependncy of a project on Windows. I'm using `stack` with the `lts-13.0` resolver, which provides GHC 8.6.3. My `stack.yaml` has the github repository as one of its `extra-deps`. More specifically, it has:

```yaml

extra-deps:
  - github: jonascarpay/apecs
    commit: "5b0585b6b435f156f638440facfdb8c02a64493d"
    subdirs: ["apecs", "apecs-stm"]

```

Running `stack build` and leaving my computer for over an hour shows it still trying to compile `apecs`. Weirdly enough it works fine on Linux and macOS, which sort of implies that I should be making a GHC issue as opposed to one in this library. Still, I figured you'd like to know about it!
